version: "3.9"
services:
  api:
    build:
      dockerfile: dev.Dockerfile
      context: .
      target: dev
    container_name: expenser-api
    image: expenser/api
    ports:
      - "8080:8080"
    volumes:
      - .:/app/expenser-api